defmodule Inexora.BatchTest do
  @moduledoc """
  Tests for the Inexora.Batch module.

  These tests verify high-level batch operations including:
  - Batch INSERT with RETURNING INTO
  - Batch INSERT without RETURNING
  """

  use ExUnit.Case, async: false

  alias Inexora.Batch
  alias Inexora.Nif

  # Helper to connect to test database
  defp connect_test_db do
    {:ok, ctx} = Nif.context_create()

    username = System.get_env("ORACLE_USER", "test_user")
    password = System.get_env("ORACLE_PASSWORD", "test_password")
    database = System.get_env("ORACLE_DATABASE", "localhost:1521/FREEPDB1")

    case Nif.conn_create(ctx, username, password, database) do
      {:ok, conn} -> {:ok, ctx, conn}
      {:error, _} = error -> error
    end
  end

  defp cleanup(ctx, conn) do
    Nif.conn_close(conn)
    Nif.context_destroy(ctx)
  end

  defp setup_test_table(conn) do
    {:ok, stmt} = Nif.stmt_prepare(conn, """
      DECLARE
        table_exists NUMBER;
      BEGIN
        SELECT COUNT(*) INTO table_exists FROM user_tables WHERE table_name = 'GTT_BATCH_MODULE_TEST';
        IF table_exists > 0 THEN
          EXECUTE IMMEDIATE 'DROP TABLE gtt_batch_module_test';
        END IF;
        EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE gtt_batch_module_test (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR2(100),
          age NUMBER
        ) ON COMMIT PRESERVE ROWS';
      END;
    """)
    {:ok, _} = Nif.stmt_execute(stmt)
    Nif.stmt_close(stmt)
    :ok
  end

  defp drop_test_table(conn) do
    {:ok, stmt} = Nif.stmt_prepare(conn, "DROP TABLE gtt_batch_module_test")
    Nif.stmt_execute(stmt)
    Nif.stmt_close(stmt)
    :ok
  end

  describe "Batch.insert/4 with RETURNING" do
    @tag :oracle_database
    test "inserts multiple rows and returns generated IDs" do
      with {:ok, ctx, conn} <- connect_test_db() do
        :ok = setup_test_table(conn)

        sql = "INSERT INTO gtt_batch_module_test (name, age) VALUES (:1, :2) RETURNING id INTO :3"
        rows = [
          ["Alice", 25],
          ["Bob", 30],
          ["Charlie", 35]
        ]

        {:ok, returned} = Batch.insert(conn, sql, rows,
          returning: [type: :number, native: :int64])

        # Should return 3 rows
        assert length(returned) == 3

        # Each returned value should be a list with one ID
        for row <- returned do
          assert length(row) == 1
          [id] = row
          assert is_integer(id)
          assert id > 0
        end

        # Verify all IDs are unique
        ids = Enum.map(returned, fn [id] -> id end)
        assert length(Enum.uniq(ids)) == 3

        drop_test_table(conn)
        cleanup(ctx, conn)
      end
    end

    @tag :oracle_database
    test "handles empty rows list" do
      with {:ok, ctx, conn} <- connect_test_db() do
        :ok = setup_test_table(conn)

        sql = "INSERT INTO gtt_batch_module_test (name, age) VALUES (:1, :2) RETURNING id INTO :3"
        rows = []

        {:ok, returned} = Batch.insert(conn, sql, rows,
          returning: [type: :number, native: :int64])

        assert returned == []

        drop_test_table(conn)
        cleanup(ctx, conn)
      end
    end

    @tag :oracle_database
    test "handles NULL values in batch insert" do
      with {:ok, ctx, conn} <- connect_test_db() do
        :ok = setup_test_table(conn)

        sql = "INSERT INTO gtt_batch_module_test (name, age) VALUES (:1, :2) RETURNING id INTO :3"
        rows = [
          ["Alice", nil],
          [nil, 30],
          ["Charlie", 35]
        ]

        {:ok, returned} = Batch.insert(conn, sql, rows,
          returning: [type: :number, native: :int64])

        assert length(returned) == 3

        # All should have generated IDs
        for row <- returned do
          [id] = row
          assert is_integer(id)
          assert id > 0
        end

        drop_test_table(conn)
        cleanup(ctx, conn)
      end
    end
  end

  describe "Batch.insert_all/3 without RETURNING" do
    @tag :oracle_database
    test "inserts multiple rows and returns count" do
      with {:ok, ctx, conn} <- connect_test_db() do
        :ok = setup_test_table(conn)

        sql = "INSERT INTO gtt_batch_module_test (name, age) VALUES (:1, :2)"
        rows = [
          ["Alice", 25],
          ["Bob", 30],
          ["Charlie", 35]
        ]

        {:ok, count} = Batch.insert_all(conn, sql, rows)

        assert count == 3

        # Verify data was inserted
        {:ok, select_stmt} = Nif.stmt_prepare(conn, "SELECT COUNT(*) FROM gtt_batch_module_test")
        {:ok, _} = Nif.stmt_execute(select_stmt)
        {:ok, true} = Nif.stmt_fetch(select_stmt)
        {:ok, db_count} = Nif.stmt_get_query_value(select_stmt, 1)
        Nif.stmt_close(select_stmt)

        db_count_int = if is_integer(db_count), do: db_count, else: String.to_integer(db_count)
        assert db_count_int == 3

        drop_test_table(conn)
        cleanup(ctx, conn)
      end
    end

    @tag :oracle_database
    test "handles empty rows list" do
      with {:ok, ctx, conn} <- connect_test_db() do
        :ok = setup_test_table(conn)

        sql = "INSERT INTO gtt_batch_module_test (name, age) VALUES (:1, :2)"
        rows = []

        {:ok, count} = Batch.insert_all(conn, sql, rows)

        assert count == 0

        drop_test_table(conn)
        cleanup(ctx, conn)
      end
    end
  end
end
